# Generated by Django 3.0.8 on 2021-04-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entree_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='SpiderVariables',
        ),
        migrations.DeleteModel(
            name='WpdVariables',
        ),
    ]
